# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "45f210e7b11de55fff0113bd59d43b0d"
application_url = "https://angry-arbor-insertion-showtimes.trycloudflare.com"
embedded = true
name = "review-app-beta"
handle = "review-app-beta"

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products, read_themes"

[auth]
redirect_urls = [
  "https://angry-arbor-insertion-showtimes.trycloudflare.com/auth/callback",
  "https://angry-arbor-insertion-showtimes.trycloudflare.com/auth/shopify/callback",
  "https://angry-arbor-insertion-showtimes.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
